#! /usr/bin/perl

use REST::Client;
use JSON;

my @params = @ARGV;
my ($controller_ip, $device)  = @params;

$controller_ip = "192.168.43.103";
$device = "of:0000000000000001";

my $client = REST::Client->new();

my $request_uri = "http://$controller_ip:8181/onos/v1/flows/$device?appId=666";
print $request_uri."\n";

$content0_t0 = "{
   \"priority\": 5000,
        \"timeout\": 1,
        \"isPermanent\": false,
        \"deviceId\": \"$device\",
        \"treatment\": {
            \"instructions\": [
            {
                \"type\": \"OUTPUT\",
                \"port\": \"1\"
            }]
        },
        \"selector\": {
            \"criteria\": [
            {
            \"type\": \"ETH_TYPE\",
            \"ethType\": \"0x806\"
            }
        ]}
    }";


$content0_t1 = "{
   \"priority\": 5000,
        \"timeout\": 1,
        \"isPermanent\": false,
        \"deviceId\": \"$device\",
        \"treatment\": {
            \"instructions\": [
            {
                \"type\": \"OUTPUT\",
                \"port\": \"1\"
            }]
        },
        \"selector\": {
            \"criteria\": [
            {
            \"type\": \"ETH_TYPE\",
            \"ethType\": \"0x806\"
            }
        ]}
    }";


$content0_t2 = "{
   \"priority\": 5000,
        \"timeout\": 1,
        \"isPermanent\": false,
        \"deviceId\": \"$device\",
        \"treatment\": {
            \"instructions\": [
            {
                \"type\": \"OUTPUT\",
                \"port\": \"1\"
            }]
        },
        \"selector\": {
            \"criteria\": [
            {
            \"type\": \"ETH_TYPE\",
            \"ethType\": \"0x806\"
            }
        ]}
    }";


$content0_t3 = "{
   \"priority\": 5000,
        \"timeout\": 1,
        \"isPermanent\": false,
        \"deviceId\": \"$device\",
        \"treatment\": {
            \"instructions\": [
            {
                \"type\": \"OUTPUT\",
                \"port\": \"1\"
            }]
        },
        \"selector\": {
            \"criteria\": [
            {
            \"type\": \"ETH_TYPE\",
            \"ethType\": \"0x806\"
            }
        ]}
    }";


$content0_t4 = "{
   \"priority\": 5000,
        \"timeout\": 5,
        \"isPermanent\": false,
        \"deviceId\": \"$device\",
        \"treatment\": {
            \"instructions\": [
            {
                \"type\": \"OUTPUT\",
                \"port\": \"1\"
            }]
        },
        \"selector\": {
            \"criteria\": [
            {
            \"type\": \"ETH_TYPE\",
            \"ethType\": \"0x806\"
            }
        ]}
    }";


$content1_t0 = "{
   \"priority\": 5001,
        \"timeout\": 1,
        \"isPermanent\": false,
        \"deviceId\": \"$device\",
        \"treatment\": {
            \"instructions\": [
            {
                \"type\": \"OUTPUT\",
                \"port\": \"1\"
            }]
        },
        \"selector\": {
            \"criteria\": [
            {
            \"type\": \"ETH_TYPE\",
            \"ethType\": \"0x806\"
            }
        ]}
    }";


$content1_t1 = "{
   \"priority\": 5001,
        \"timeout\": 1,
        \"isPermanent\": false,
        \"deviceId\": \"$device\",
        \"treatment\": {
            \"instructions\": [
            {
                \"type\": \"OUTPUT\",
                \"port\": \"1\"
            }]
        },
        \"selector\": {
            \"criteria\": [
            {
            \"type\": \"ETH_TYPE\",
            \"ethType\": \"0x806\"
            }
        ]}
    }";


$content1_t2 = "{
   \"priority\": 5001,
        \"timeout\": 1,
        \"isPermanent\": false,
        \"deviceId\": \"$device\",
        \"treatment\": {
            \"instructions\": [
            {
                \"type\": \"OUTPUT\",
                \"port\": \"1\"
            }]
        },
        \"selector\": {
            \"criteria\": [
            {
            \"type\": \"ETH_TYPE\",
            \"ethType\": \"0x806\"
            }
        ]}
    }";


$content2_t0 = "{
   \"priority\": 5002,
        \"timeout\": 1,
        \"isPermanent\": false,
        \"deviceId\": \"$device\",
        \"treatment\": {
            \"instructions\": [
            {
                \"type\": \"OUTPUT\",
                \"port\": \"1\"
            }]
        },
        \"selector\": {
            \"criteria\": [
            {
            \"type\": \"ETH_TYPE\",
            \"ethType\": \"0x806\"
            }
        ]}
    }";


$content2_t1 = "{
   \"priority\": 5002,
        \"timeout\": 8,
        \"isPermanent\": false,
        \"deviceId\": \"$device\",
        \"treatment\": {
            \"instructions\": [
            {
                \"type\": \"OUTPUT\",
                \"port\": \"1\"
            }]
        },
        \"selector\": {
            \"criteria\": [
            {
            \"type\": \"ETH_TYPE\",
            \"ethType\": \"0x806\"
            }
        ]}
    }";


# part 1
$client->POST($request_uri, $content0_t0, {'Authorization' => 'Basic b25vczpyb2Nrcw==', 'Content-Type' => 'application/json', 'Accept' => 'application/json'});
if( ($client->responseCode() eq '200') or
    ($client->responseCode() eq '201')){
    print "Added Successfully; content0_t1\n";
}
else
{
    print "Error! Response Code ".$client->responseCode()."\n";
    print "Response\n".$client->responseContent()."\n";
}

sleep(1);

$client->POST($request_uri, $content0_t1, {'Authorization' => 'Basic b25vczpyb2Nrcw==', 'Content-Type' => 'application/json', 'Accept' => 'application/json'});
if( ($client->responseCode() eq '200') or
    ($client->responseCode() eq '201')){
    print "Added Successfully; content1_t2\n";
}
else
{
    print "Error! Response Code ".$client->responseCode()."\n";
    print "Response\n".$client->responseContent()."\n";
}

sleep(1);


# part 2
$client->POST($request_uri, $content0_t2, {'Authorization' => 'Basic b25vczpyb2Nrcw==', 'Content-Type' => 'application/json', 'Accept' => 'application/json'});
if( ($client->responseCode() eq '200') or
    ($client->responseCode() eq '201')){
    print "Added Successfully; content0_t1\n";
}
else
{
    print "Error! Response Code ".$client->responseCode()."\n";
    print "Response\n".$client->responseContent()."\n";
}

$client->POST($request_uri, $content1_t0, {'Authorization' => 'Basic b25vczpyb2Nrcw==', 'Content-Type' => 'application/json', 'Accept' => 'application/json'});
if( ($client->responseCode() eq '200') or
    ($client->responseCode() eq '201')){
    print "Added Successfully; content0_t1\n";
}
else
{
    print "Error! Response Code ".$client->responseCode()."\n";
    print "Response\n".$client->responseContent()."\n";
}

sleep(1);

# part 3
$client->POST($request_uri, $content0_t3, {'Authorization' => 'Basic b25vczpyb2Nrcw==', 'Content-Type' => 'application/json', 'Accept' => 'application/json'});
if( ($client->responseCode() eq '200') or
    ($client->responseCode() eq '201')){
    print "Added Successfully; content0_t1\n";
}
else
{
    print "Error! Response Code ".$client->responseCode()."\n";
    print "Response\n".$client->responseContent()."\n";
}

sleep(1);

# part 4
$client->POST($request_uri, $content1_t1, {'Authorization' => 'Basic b25vczpyb2Nrcw==', 'Content-Type' => 'application/json', 'Accept' => 'application/json'});
if( ($client->responseCode() eq '200') or
    ($client->responseCode() eq '201')){
    print "Added Successfully; content0_t1\n";
}
else
{
    print "Error! Response Code ".$client->responseCode()."\n";
    print "Response\n".$client->responseContent()."\n";
}

$client->POST($request_uri, $content2_t0, {'Authorization' => 'Basic b25vczpyb2Nrcw==', 'Content-Type' => 'application/json', 'Accept' => 'application/json'});
if( ($client->responseCode() eq '200') or
    ($client->responseCode() eq '201')){
    print "Added Successfully; content0_t1\n";
}
else
{
    print "Error! Response Code ".$client->responseCode()."\n";
    print "Response\n".$client->responseContent()."\n";
}

sleep(1);

# part 5
$client->POST($request_uri, $content0_t4, {'Authorization' => 'Basic b25vczpyb2Nrcw==', 'Content-Type' => 'application/json', 'Accept' => 'application/json'});
if( ($client->responseCode() eq '200') or
    ($client->responseCode() eq '201')){
    print "Added Successfully; content1_t2\n";
}
else
{
    print "Error! Response Code ".$client->responseCode()."\n";
    print "Response\n".$client->responseContent()."\n";
}

sleep(1);

$client->POST($request_uri, $content1_t2, {'Authorization' => 'Basic b25vczpyb2Nrcw==', 'Content-Type' => 'application/json', 'Accept' => 'application/json'});
if( ($client->responseCode() eq '200') or
    ($client->responseCode() eq '201')){
    print "Added Successfully; content1_t2\n";
}
else
{
    print "Error! Response Code ".$client->responseCode()."\n";
    print "Response\n".$client->responseContent()."\n";
}

$client->POST($request_uri, $content2_t1, {'Authorization' => 'Basic b25vczpyb2Nrcw==', 'Content-Type' => 'application/json', 'Accept' => 'application/json'});
if( ($client->responseCode() eq '200') or
    ($client->responseCode() eq '201')){
    print "Added Successfully; content1_t2\n";
}
else
{
    print "Error! Response Code ".$client->responseCode()."\n";
    print "Response\n".$client->responseContent()."\n";
}

$client->GET($request_uri, {'Authorization' => 'Basic b25vczpyb2Nrcw==', 'Accept' => 'application/json'});

sleep(1);

$response = from_json($client->responseContent());

$size = scalar @{$response->{'flows'}};

$del_rule=-1;
for(my $j=0; $j < $size; $j++) {
    if ($response->{'flows'}[$j]->{'priority'} == 5000) {
        $id = $response->{'flows'}[$j]->{'id'}; print "\n";
    $del_rule=$response->{'flows'}[$j]->{'priority'};
    }
}

my $request_uri_1 = "http://$controller_ip:8181/onos/v1/flows/$device/$id";
$header={'Authorization' => 'Basic b25vczpyb2Nrcw==', 'Accept' => 'application/json'};

if ($del_rule != -1) {
    $client->DELETE($request_uri_1, $header);
    print "delete_rule=".$del_rule."\n";
    print "Response Code ".$client->responseCode()."\n";
}
