#! /usr/bin/perl

use REST::Client;
use JSON;


my @params = @ARGV;
my ($controller_ip, $device)  = @params;

$controller_ip = "192.168.43.103";
$device = "of:0000000000000001";

my $client = REST::Client->new();

my $request_uri = "http://$controller_ip:8181/onos/v1/flows/$device?appId=666";
print $request_uri."\n";

my $step=5;
for (my $i=0; $i < 5; $i++) {
    my $time = $i + $step;
    $content = "{
        \"priority\": 500$i,
        \"timeout\": $time,
        \"isPermanent\": false,
        \"deviceId\": \"$device\",
        \"treatment\": {
            \"instructions\": [
            {
                \"type\": \"OUTPUT\",
                \"port\": \"1\"
            }]
        },
        \"selector\": {
            \"criteria\": [
            {
            \"type\": \"ETH_TYPE\",
            \"ethType\": \"0x806\"
            }
        ]}
    }";
    
    $client->POST($request_uri, $content, {'Authorization' => 'Basic b25vczpyb2Nrcw==', 'Content-Type' => 'application/json', 'Accept' => 'application/json'});

    if( ($client->responseCode() eq '200') or
	($client->responseCode() eq '201')){
         print "Added Successfully\n";
    }
    else
    {
        print "Error! Response Code ".$client->responseCode()."\n";
        print "Response\n".$client->responseContent()."\n";
    }
}
